---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# planex

<!-- badges: start -->
<!-- badges: end -->

FunĂ§Ăµes e bancos de dados para a disciplina de Planejamento de Experimentos. 

## InstalaĂ§Ă£o

VocĂª pode instalar o pacote planex da seguinte forma:

``` r
install.packages('planex', repos = c('https://fndemarqui.r-universe.dev', 'https://cloud.r-project.org'))
```

## Exemplo

```{r saquinhos}
library(planex)
data(saquinhos)
saquinhos$concentracao <- as.factor(saquinhos$concentracao)
mod <- aov(resistencia ~ concentracao, data = saquinhos)
plotResiduals(mod)
testResiduals(mod)
summary(mod)
```

Realizando as comparaĂ§Ăµes mĂºltiplas:

```{r}
library(agricolae)
library(multcomp)
library(emmeans)

comp1 <- HSD.test(mod, "concentracao", group = FALSE)
comp2 <- glht(mod, linfct = mcp(concentracao = "Tukey"))
comp3 <- emmeans(mod, pairwise ~ concentracao, adjust = "tukey")

comp1$comparison
summary(comp2)
comp3$contrasts
```

